export const FONT_FAMILY_OPTIONS = [
  { label: 'AbrilFatface', value: '"AbrilFatface", serif' },
  { label: 'AlfaSlabOne', value: '"AlfaSlabOne", serif' },
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'AtkinsonHyperlegibleMono', value: '"AtkinsonHyperlegibleMono", monospace' },
  { label: 'Caprasimo', value: '"Caprasimo", cursive' },
  { label: 'Fixture', value: '"Fixture", sans-serif' },
  { label: 'Gelasio', value: '"Gelasio", serif' },
  { label: 'Inter', value: 'Inter, "Segoe UI", sans-serif' },
  { label: 'MerriweatherSans', value: '"MerriweatherSans", sans-serif' },
  { label: 'MPLUS1Code', value: '"MPLUS1Code", monospace' },
  { label: 'Oi', value: '"Oi", cursive' },
  { label: 'Ramaraja', value: '"Ramaraja", serif' },
  { label: 'REM', value: '"REM", sans-serif' },
  { label: 'Roboto', value: 'Roboto, "Segoe UI", sans-serif' },
  { label: 'Ubuntu', value: '"Ubuntu", sans-serif' },
  { label: 'Ultra', value: '"Ultra", serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: '"Times New Roman", serif' },
  { label: 'Courier New', value: '"Courier New", monospace' },
]
