export const FONT_FAMILY_OPTIONS = [
  { label: 'AbrilFatface', value: '"AbrilFatface", serif' },
  { label: 'Alyamama', value: '"Alyamama", sans-serif' },
  { label: 'AlfaSlabOne', value: '"AlfaSlabOne", serif' },
  { label: 'Amiri', value: '"Amiri", serif' },
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'AtkinsonHyperlegibleMono', value: '"AtkinsonHyperlegibleMono", monospace' },
  { label: 'BadeenDisplay', value: '"BadeenDisplay", cursive' },
  { label: 'Cairo', value: '"Cairo", sans-serif' },
  { label: 'Caprasimo', value: '"Caprasimo", cursive' },
  { label: 'Changa', value: '"Changa", sans-serif' },
  { label: 'ElMessiri', value: '"ElMessiri", sans-serif' },
  { label: 'Fixture', value: '"Fixture", sans-serif' },
  { label: 'Gelasio', value: '"Gelasio", serif' },
  { label: 'Inter', value: 'Inter, "Segoe UI", sans-serif' },
  { label: 'Lalezar', value: '"Lalezar", cursive' },
  { label: 'MerriweatherSans', value: '"MerriweatherSans", sans-serif' },
  { label: 'MPLUS1Code', value: '"MPLUS1Code", monospace' },
  { label: 'Oi', value: '"Oi", cursive' },
  { label: 'Ramaraja', value: '"Ramaraja", serif' },
  { label: 'ReemKufi', value: '"ReemKufi", sans-serif' },
  { label: 'REM', value: '"REM", sans-serif' },
  { label: 'Roboto', value: 'Roboto, "Segoe UI", sans-serif' },
  { label: 'Rubik', value: '"Rubik", sans-serif' },
  { label: 'Ubuntu', value: '"Ubuntu", sans-serif' },
  { label: 'Ultra', value: '"Ultra", serif' },
  { label: 'Zain', value: '"Zain", sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Times New Roman', value: '"Times New Roman", serif' },
  { label: 'Courier New', value: '"Courier New", monospace' },
]
